### ISSUE TITLE
What is the core idea of ProSelfLC?

### ISSUE THREAD

**Issue by guotong1988** [XinshaoAmosWang/ProSelfLC#1]
I am new to ProSelfLC. Thank you very much! @XinshaoAmosWang

**Comment by xinshao-wang** [comment]
@guotong1988 Thanks for your interest. 
ProSelfLC relates to self knowledge distillation, label correction in terms of its similarity structure definition, in defence of optimisation via entropy minimisation, predictive uncertainty, etc. 
The core idea is how to trust a learner progressively as its knowledge increases during training.
